### ISSUE TITLE
Upgrade to openhab 4.X.X

### ISSUE THREAD

**Issue by garglkarg** [esdeboer/openhab2-addons#2]
Is it easily possible to make the snapcast binding available for openhab 4? 
(it somehow unintentionally upgraded me and this binding is the only reason for my retrograde...)

**Comment by corubba** [comment]
It appears a simple version-bump in the [pom.xml](https://github.com/esdeboer/openhab2-addons/blob/snapcast/bundles/org.openhab.binding.snapcast/pom.xml#L10) from `3.1.0-SNAPSHOT` to `4.0.2`, followed by a rebuild, is enough to make it work again.

[org.openhab.binding.snapcast-4.0.2.jar.gz](https://github.com/esdeboer/openhab2-addons/files/12445242/org.openhab.binding.snapcast-4.0.2.jar.gz)

**Comment by garglkarg** [comment]
great! works for me - many thanks

**Comment by esdeboer** [comment]
Thanks @corubba for updating the pom and providing a working version.

It seems one config file also changed, that's why it wasn't showing in the UI, that should now also be fixed by the latest release
[org.openhab.binding.snapcast-4.2.0-SNAPSHOT.jar](https://github.com/esdeboer/openhab2-addons/releases/download/snapcast-4.2.0-SNAPSHOT/org.openhab.binding.snapcast-4.2.0-SNAPSHOT.jar)
